language: node_js
node_js:
- '0.10'
- '0.8'
addons:
  sauce_connect: true
before_install:
- npm install -g grunt-cli
- npm install -g npm
install:
- npm install
before_script:
- export NODE_DEBUG="webfiber request"
env:
  global:
  - secure: P8+om77jHpyd/RrsQyuI2M7zILRq0ufQyugxj519D9mPUUpZu3vED7EyXk40RTaC+zkMsih4EbNtby79fo5j069S8ExLwUor7Q5NAbT17NfphldaTwYIWj46qc9wHSdbEnbHRI8yA0j2PF5W3hk8lM2tyt+QlvPb24oLWWC0ulk=
  - secure: MXt+fXdtGYXJ2OnKsZrgHeRSUKjsBmyJ8hzIwSBUOI8ui/0tAb19LGOV27MWxyPXp443hliAGvC5eCEamDNOmIW4RzrGclFxqvNvrqZs62vqai9Klyyr7Tjb0atWhFZqSdDCD2qo1nB6M49o1+a1nMr7m+zL8g0uabN/eCYiv1Y=
